info:
  description: This is a sample API
  title: Your API
  version: 1.0.0
openapi: 3.0.3
paths:
  /:
    get:
      operationId: health__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Health
